# Generated by Django 5.1.4 on 2025-01-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzMaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
