# Generated by Django 5.1.4 on 2025-01-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzMaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='option',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
